### ISSUE TITLE
shortcodes in archive description

### ISSUE THREAD

**Issue by m-e-h** [cedaro/cpt-archives#7]
Any plans to allow shortcodes?
I'm using Hybrid-Core in my theme which already filters `get_the_archive_description` for shortcodes.
https://github.com/justintadlock/hybrid-core/blob/master/inc/functions-filters.php#L18

`post_type_archive_description` overrides it, though.

**Comment by m-e-h** [comment]
`get_the_archive_description` was just reworked in hybrid-core, so shortcodes work for me now on cpt-archives. 
I'll close this now. Might be a nice feature to add, though, if you wanna re-open. 
Thanks for the awesome plugin, btw! :smiley:

**Comment by bradyvercher** [comment]
Sorry for the slow response on this. Glad to hear you were able to get things working. I'm not keen on processing the text in this plugin, but it probably wouldn't hurt to run `ArchiveHookProvider::post_type_archive_description()` a little earlier so it doesn't replace the text after something like Hybrid core has already processed it.
