### ISSUE TITLE
WordPress 4.4 compatibility

### ISSUE THREAD

**Issue by klihelp** [cedaro/cpt-archives#9]
Plugin is not working with WordPress 4.4
- In admin: archive submenu is registered, but the page gives an wp error: 
```You are not allowed to edit posts in this post type.```

**Comment by bradyvercher** [comment]
That should have been fixed in #8, although it's not in a tagged release yet. Are you using the develop branch or 3.0?

**Comment by klihelp** [comment]
yes, works with the develop brach, thanks
